<a href="https://colab.research.google.com/github/ckatsoulas/bootstrap/blob/main/%CE%91%CE%BD%CF%84%CE%AF%CE%B3%CF%81%CE%B1%CF%86%CE%BF_01_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tickable Exercise 1

No due date on this one.

This notebook contains a hands-on tutorial on working with Jupyter notebooks. At the end, there are some exercises on programming in Python, based on the material in the [first lecture on Python](./Lecture_01b_FirstLookAtPython.ipynb); before continuing make sure that you have worked through this notebook first.

Please go through the following exercises before the computer lab on the due date shown above. If you get stuck, have any questions or anything is unclear, please speak to your tutor in this computer lab.

## Working with Jupyter notebooks
When you open a Jupyter notebook in a web browser, the header will list the name of the currently opened file, followed by a menubar and a buttonbar, as shown in the following picture:

![Header of Jupyter notebooks](./figures/jupyter_header.png "Header of Jupyter notebooks")

Jupyter notebooks are organised into **cells** which you can select by clicking on them. The currently selected cell is marked with a coloured bar on the left. A cell can contain either code or markdown text. You can change the type of the current cell with the dropdown menu in the button bar at the top of the window as shown here:

![Cell type selector](./figures/cell_type_selector.png "Cell type selector")

You can add new cells and delete existing cells with the <i class="fa fa-plus"></i> and <i class="fa fa-cut"></i> symbols in the buttonbar:

![Adding and deleting cells](./figures/button_bar_add_cut.png "Adding and deleting cells")

It is also possible to copy cells, move them up and down, merge them etc. via the ''Edit'' menu item in the menu bar.

**While working on an exercise, you should regularly save your work by clicking the <i class="fa fa-save"></i> symbol in the button bar.** 

![Saving notebook](./figures/button_bar_save.png "Saving notebook")

If you do not do this, your work will be lost when you close the window with the Jupyter notebook.

### Markdown cells
Ok, so let's create two new cells in our notebook. Turn the first of these two cells into a markdown cell as explained above. In this cell we can now enter text. This is useful if we want to provide additional context for our work. The nice thing about markdown is that we can use special formatting for headings and to highlight text in *italic* or **bold** font. It is also possible to write [mathematical equations](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Typesetting%20Equations.html).

Let's try this out. Enter the following text into the markdown cell that you created:

```
## This is a heading
This box contains some text in *italic* and some text in **bold**.

Here is a list of animals:
* cat
* dog
* rabbit
```

You will notice that the text already gets pre-formatted by Jupyter. The cell should look like this:

![Raw markdown cell](./figures/markdown_raw.png "Raw markdown cell")

Next, press the ''<i class="fa fa-play"></i> Run'' button in the button bar for Jupyter to apply the formatting (alternatively, you can press the ''Shift'' and ''Enter'' keys on your keyboard).

If everything has worked correctly, you should see this:

![Formatted markdown cell](./figures/markdown_formatted.png "Formatted markdown cell")

You can go back to editing the contents of the markdown cell by double clicking it. Try this out now and add some more text.

More information on markdown can be found in the [Jupyter documentation](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html#). For this course you do not need to learn the details of markdown syntax, but you might find the basics useful for keeping notes and documenting your work.

### Python code cells
You can enter Python code in cells that are not markdown cells (by default all newly created cells are code cells). Those cells are labelled with an `In [ ]` on the left, as in the following example:

![Empty code cell](./figures/code_cell_before.png "Empty code cell")

Let's do a simple computation. Go to a code cell in your `Tickable1_USERNAME` notebook, enter `1+2*5` and press the ''<i class="fa fa-play"></i> Run'' button (or press `Shift+Enter` on your keyboard). Python will execute the code and print out the output of the calculation:

![Code cell after execution](./figures/code_cell_after.png "Code cell after execution")

Note how the label on the left has changed to `In [1]` and the corresponding output is labelled with `Out [1]`. If you execute more than one cell the number in square brackets is used to label the order in which the cells were executed.

We can enter more than one Python command in a cell. For example, we could import the numpy library, use the function `exp()` to compute $e^3$, store the result in some variable `exp3` and print out the result as follows:

![Code cell with more complex Python code](./figures/code_cell_exp3.png "Code cell with more complex Python code")

## Some Python programming exercises
It's your turn now. Use your notebook `Tickable1_USERNAME` to work through the following programming exercises. Show your computations to your tutor in your programming lab; don't forget to save your work at regular intervals.

### &#9745; Exercise 1: using Python as a calculator
Write Python code to compute the following quantities. You should do each calculation in a separate cell.

* $7/8$ (there are two ways of doing this, depending on whether we divide with or without remainder)
* $7^3+2^3$
* $1\cdot 2\cdot 3\cdot 4 \cdot 5 \cdot 6\cdot 7 \cdot 8$
* $2^{3+4^2}$
* $10000^4-1$

### &#9745; Exercise 2: using variables
Write Python code which computes the volume of a pyramid which has a given height $H$ and whose base is a rectangle of width $W$ and length $L$; in this case the volume $V$ is given by

$$
V = \frac{1}{3} H\cdot W\cdot L\qquad(\dagger)
$$

For this, introduce variables called `height`, `width` and `length`, and assign the values $H=3$, $W=2$, $L=5$ to them. Then use the formula in Eq. $(\dagger)$ for the volume and assign a new variable `volume` to the result. Use the `print()` function to print out the value of the variable `volume`.

### &#9745; Exercise 3: manipulating lists

* Create a list with the elements $1,3,5,7,9$. Change the pen-ultimate entry in this list from $5$ to $-5$ and print the list before and after this transformation.
* Concatenate the lists $[0,2,4,6]$ and $[1,3,5,7]$ and print the result.

### &#9745; Exercise 4: working with numpy
Import the numpy library in such a way that you can use it with `np.`, then compute the following quantities

* $e^{5}$
* $\sin(\pi/7)$
* $\sqrt{e^{3}+2}$

Consider the following code:
```Python
np.log2([1,2,4,8,32,512])
```

Can you work out what it does? You might want to look up the `log2` function on the [numpy documentation page](https://numpy.org/doc/stable/reference/routines.math.html).

### &#9745; Exercise 5: vectors and matrices
Execute the following code to create the $2\times 2$ matrix $\begin{pmatrix}1&2\\3&4\end{pmatrix}$:
```Python
A = np.array([[1,2],[3,4]])
```
(this will only work if you imported the numpy library in the previous exercise).

In the same cell, write Python code to create the $3\times 2$ matrix $D=\begin{pmatrix}1&2\\3&4\\5&6\end{pmatrix}$.

* Compute the matrix product $A\circ A$ and the componentwise product $A\odot A$.
* Consider the following expressions:
    - `A@D`
    - `D@A`
    - `A*D`
    - `D*A`
  
  By executing these expressions, check which ones are valid and try to understand why.
  
Write some code to compute the matrix-vector product $w=B^Tv$ where

$$
B = \begin{pmatrix}1&8\\2&9\\-1&4\\0&2\end{pmatrix}\qquad
v = \begin{pmatrix}-3\\4\\6\\-2\end{pmatrix}
$$

There are (at least) three different ways of doing this, try to implement as many as possible.

In [ ]:
import numpy as np
A = np.array([[1,2],[3,4]])
D = np.array([[1,2],[3,4],[5,6]])
print(A)
print(D)
#For matrix multiplication (matrix product), the number of columns in the first matrix must be equal to the number of rows in the second matrix. 
#The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix
#see https://en.wikipedia.org/wiki/Matrix_multiplication
# MATRIX PRODUCT
MP = np.matmul(A,A)
print(MP)
#COMPONENT WISE PRODUCT
#component wise product will multiply per element
CWP = np.multiply(A,A)
print (CWP)
# A@D stands for matrix product. Columns of A must be equal to the rows of D. They do not. Columns of A = 2, rows of D = 3. 
# print(A@D) produces an error
# print (D@A) is valid as columns of D = 2 and rows of A = 2
print(D@A)
# A*D stands for element-wise operator. Matrices must have the same shape. They do not. (A is 2X2, D is 3X2).
# print(A*D) is not valid
# print(D*A) is not valid

# code to compute the matrix-vector product  w=B**T * v  
# see https://mathinsight.org/matrix_vector_multiplication
# B to the power of T (B**T) means to transpose a matrix (rows to columns and columns to rows)
# see https://www.cuemath.com/algebra/transpose-of-a-matrix/
# B must be transposed in order to compute the product with the vector
print ("original B is")
B = np.array( [ [1,8],[2,9],[-1,4],[0,2] ] )
print(B)
print ("B after transpose is ")
BT = np.transpose(B)
print(BT)
U = np.array( [ [-3],[4],[6],[-2] ])
print("U")
print(U)
print("BT*U")
print(BT@U)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]
 [23 34]]
original B is
[[ 1  8]
 [ 2  9]
 [-1  4]
 [ 0  2]]
B after transpose is 
[[ 1  2 -1  0]
 [ 8  9  4  2]]
U
[[-3]
 [ 4]
 [ 6]
 [-2]]
BT*U
[[-1]
 [32]]
